### ISSUE TITLE
Release, publish and document how to use the Action in GitHub Actions workflows

### ISSUE THREAD

**Issue by umarcor** [umarcor/qus#7]
https://github.com/dbhi/qus/tree/main/action

```yml
    - uses: dbhi/qus@action-v0
```

```yml
    - uses: dbhi/qus@action-v0
      with:
        targets: >
          arm
          aarch64
```
